version: '2'
services:
  myztl3-app:
    image: myztl3
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,swagger
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - SPRING_DATASOURCE_URL=jdbc:postgresql://myztl3-postgresql:5432/myZTL3
      - JHIPSTER_SLEEP=30 # gives time for other services to boot before the application
    ports:
      - 8081:8081
  myztl3-postgresql:
    extends:
      file: postgresql.yml
      service: myztl3-postgresql
